### PR TITLE
Address failure to update under some cases

### PR DESCRIPTION
**Pull request by sk-ys**
Related to #53 and #55, I found that in some cases the update failed when following plugins were used.
- redmineup, redmine_checklists plugin
- redmineup, redmineup_tags plugin

Therefore, I temporarily reviewed the process of updating issue attributes.
However, the aforementioned plugins are not compatible completely.

### CODE REVIEW

**Comment by MayamaTakeshi** [comment]
I did a quick test. I have only plugin redmine_rt installed and I noticed the last changes inserted a regression and the 'related issues' are not updated in real time anymore.

**Comment by sk-ys** [comment]
I'm sorry, I commited to a branch that is not the latest.
I'm forcing update on the same branch. Please check again.

**Comment by MayamaTakeshi** [comment]
OK. I tested with only my plugin installed and since there was no impact I merged your changes (since I am not using redmine_checklists/redmine_tags, I am not checking for conflicts with them).

**Comment by sk-ys** [comment]
Thank you so much.

**Pull request merged**
